GET http://localhost:8000/api

###
GET http://localhost:8000/api/hello

###
GET http://localhost:8000/api/hello?name=Claudio

### Delete User By Id
DELETE http://localhost:8000/api/users?id=6516932f4b6ac95388e11701

### Delete User By Id Without Id
DELETE http://localhost:8000/api/users

### Update User By Id
PUT http://localhost:8000/api/users?id=6515cdd150c910bba2b8be3b
Content-Type: application/json

{
    "name": "Lucia",
    "email": "lucia@meloinvento.com",
    "age": 40
}

### Obtain User Data  
GET http://localhost:8000/api/auth/me?id=65195867ab03360348b2c7b5
X-Access-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imx1Y2lhQG1lbG9pbnZlbnRvLmNvbSIsImlhdCI6MTY5NjE3OTM0NSwiZXhwIjoxNjk2MjY1NzQ1fQ.E9-225H_XLTWeIYqK_M1ccOWi2M_6Mu-qG9RD5l7FXc

### Obtain User Data With Invalid Token
GET http://localhost:8000/api/auth/me?id=65195867ab03360348b2c7b5
X-Access-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imx1Y2lhQG1lbG9pbnZlbnRvLmNvbSIsImlhdCI6MTY5NjE3OTM0NSwiZXhwIjoxNjk2MjY1NzQ1fQ.E9-225H_XLTWeIYqK_M1ccOWi2M_6Mu-qG9RD5l7FX

### Obtain User Data Without ID 
GET http://localhost:8000/api/auth/me
X-Access-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imx1Y2lhQG1lbG9pbnZlbnRvLmNvbSIsImlhdCI6MTY5NjE3OTM0NSwiZXhwIjoxNjk2MjY1NzQ1fQ.E9-225H_XLTWeIYqK_M1ccOWi2M_6Mu-qG9RD5l7FXc

### Obtain User Data With Invalid ID (TODO)
GET http://localhost:8000/api/auth/me?id=65195867ab03360348b25
X-Access-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imx1Y2lhQG1lbG9pbnZlbnRvLmNvbSIsImlhdCI6MTY5NjE3OTM0NSwiZXhwIjoxNjk2MjY1NzQ1fQ.E9-225H_XLTWeIYqK_M1ccOWi2M_6Mu-qG9RD5l7FXc
